---
title: "GD_property"
author: "John Park"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(sf)
library(sp)
```

## NHV property data (all 2017 numbers)
```{r}
full_df <- readRDS("../data/raw/property/full_df.RDS")

# function to get assessment
get_ass <- function(pid) {
  file <- paste0("../data/raw/property/valuations/", pid, ".RDS")
  dat <- readRDS(file)[[1]] 
  if(dat[1,1] != "No Data for Assessment History") {
    assessment <- dat %>% 
      dplyr::filter(`Valuation Year` == 2017) %>% 
      select(Total)
    return(assessment$Total)
  }
  else return(NA)
}

# non-tax paying properties
relig <- c("churc", "prayer", "congreg", "baptist", "varic", "catholic", 
           "praise", "deliverance", "chapel", "saint", "pentec", "methodi",
           "parish", "st luke")
other <- c("yale", "city of", "cit of", "preparatory", "prepatory", "cornell scott")
non_tax <- c(relig, other) %>%
  paste(collapse = "|") %>% 
  substr(0, nchar(.)-1)

# use sds674 files for point to address
adds <- read_csv("../data/sds674/nhv_addresses.csv") %>% 
  dplyr::select(-`Unique ID`, -City, -State, -ZIP)
properties <- read_csv("../data/sds674/property_info.csv")
rawproperties <- read_sf(dsn="../data/sds674/arcgis_output/nhv_addresses_GeocodeAddress.shp") %>% 
  bind_cols(adds) %>% 
  bind_cols(properties)
```

## Dixwell Ave.
```{r}
dixwellave_raw <- full_df %>% 
  filter(str_detect(address, "DIXWELL")) %>% 
  select(address, owner, pid)

dixwellave_df <- dixwellave_raw %>% 
  mutate(assessment = map(.$pid, get_ass) %>% unlist()) %>% 
  mutate(assessment = parse_number(assessment)) %>% 
  mutate(assessment = as.numeric(assessment)) %>% 
  mutate(tax = assessment * 0.4298) %>% 
  mutate_if(is.character, tolower) %>% 
  filter(!str_detect(owner, non_tax))

dixwellave_df %>% summarize(tot = sum(tax))

# dixwellave_df %>% arrange(desc(assessment))
```

## Dixwell
```{r}
dixwell_sf <- cwi::new_haven_sf %>% filter(name == "Dixwell")
dixwell_raw <- rawproperties[which(st_within(rawproperties$geometry, dixwell_sf) %>% 
  as.numeric()==1),] %>% 
  as_tibble() %>% 
  select(address, owner) %>% 
  left_join(full_df) %>% # go back to using full_df (contains pid)
  select(address, owner, pid) %>% 
  drop_na()

xtra_non_tax <- c("state of connecticut", 
                  "neighborhood housing services",
                  "youth continuum inc", "land trust", non_tax) %>% 
  paste(collapse="|") %>% 
  substr(0, nchar(.)-1)

dixwell_df <- dixwell_raw %>% 
  mutate(assessment = map(.$pid, get_ass) %>% unlist()) %>% 
  mutate(assessment = parse_number(assessment)) %>% 
  mutate(assessment = as.numeric(assessment)) %>% 
  mutate(tax = assessment * 0.4298) %>% 
  mutate_if(is.character, tolower) %>% 
  filter(!str_detect(owner, xtra_non_tax)) %>% 
  drop_na()

dixwell_df %>% summarize(tot = sum(tax))

dixwell_df %>% arrange(desc(assessment))
```


## Newhallville
```{r}
nhville_sf <- cwi::new_haven_sf %>% filter(name == "Newhallville")
adds <- read_csv("../data/sds674/nhv_addresses.csv") %>% 
  dplyr::select(-`Unique ID`, -City, -State, -ZIP)
properties <- read_csv("../data/sds674/property_info.csv")
rawproperties <- read_sf(dsn="../data/sds674/arcgis_output/nhv_addresses_GeocodeAddress.shp") %>% 
  bind_cols(adds) %>% 
  bind_cols(properties)
nhville_raw <- rawproperties[which(st_within(rawproperties$geometry, nhville_sf) %>% 
  as.numeric()==1),] %>% 
  as_tibble() %>% 
  select(address, owner) %>% 
  left_join(full_df) %>% # go back to using full_df (contains pid)
  select(address, owner, pid) %>% 
  drop_na()

xtra_non_tax <- c("mutual housing association of south cent", 
                  "housing authority of new haven",
                  "youth continuum inc", "land trust", non_tax) %>% 
  paste(collapse="|") %>% 
  substr(0, nchar(.)-1)

nhville_df <- nhville_raw %>% 
  mutate(assessment = map(.$pid, get_ass) %>% unlist()) %>% 
  mutate(assessment = parse_number(assessment)) %>% 
  mutate(assessment = as.numeric(assessment)) %>% 
  mutate(tax = assessment * 0.4298) %>% 
  mutate_if(is.character, tolower) %>% 
  filter(!str_detect(owner, xtra_non_tax)) %>% 
  drop_na()

nhville_df %>% summarize(tot = sum(tax))

nhville_df %>% arrange(desc(assessment))
```



## GD Data
```{r}
raw <- readxl::read_excel("../data/clean/Great Depression Buildings.xlsx") %>% janitor::clean_names()
df <- raw %>% select(exemption = current_tax_exemption, year=year_built) %>% 
  mutate(year=as.numeric(year)) %>% 
  drop_na() %>% 
  group_by(year) %>% 
  summarise(val=sum(exemption)) %>% 
  mutate(val=cumsum(val))
```

```{r}
ref_1 <- dixwellave_df %>% summarize(tot = sum(tax)) %>% unlist()

df %>% 
  ggplot(aes(x=year, y=val)) +
  geom_rect(aes(xmin=lag(year), xmax=year, ymin=0, ymax=Inf, alpha=0.7)) +
  geom_vline(aes(xintercept = year), color = "white", size = 0.4) +
  geom_hline(aes(yintercept = ref_1), 
             color = "gray50", size = 0.7, linetype = "22") +
  geom_text(aes(label = "Property tax of all buildings\non Dixwell Ave in NHV, 2017.", x = 1935, y = ref_1),
            hjust = 0.75, vjust = 1.5, color = "gray20", size = 2.5) +
  geom_hline(aes(yintercept = 25e6), color = "gray50", size = 0.7, linetype = "22") +
  geom_text(aes(label = "reference 2", x = 1935, y = 25e6),
            hjust = 0.75, vjust = 2, color = "gray20", nudge_y = -20, nudge_x = 0, size = 2.5) +
  geom_point(color = "gray30", size = 4) +
  theme(legend.position = "none",
        plot.caption = element_text(margin = margin(2, 2, 1, 0, "lines"))) +
    labs(x = "built in (cumulative)", y = "Tax exemption (2017)",
       title = "Tax exemption of Yale properties acquired during the Great Depression",
       subtitle = "Surpass reference 2",
       caption = "Source: City of New Haven") +
  scale_x_continuous(breaks = seq(1929, 1935, by = 1)) +
  scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6))
```

